bankslip_lst = [
    {
        "id": 1,
        "BankSlipDate": "2020-09-11",
        "CustomerID": "SQ75BAGU",
        "BankCode": "S2ZU",
        "BankSlipCurrency": "USD",
        "BankSlipAmount": "695.00",
        "CustomerName": "TSMC",
        "BankSlipCustomer": "QCLSPF",
        "Country": "USA",
        "FilePath": "/files/9ICN7RSUQZ.pdf",
        "PredictType": "F",
        "ProcessStatus": "Finish",
        "ReferenceNumber": "AM8JV7BQY6RB",
        "RemitType": "Online",
        "BankSlipRemark": "Remark 19",
        "ChangeDate": "2024-08-21",
        "ArNo": "H2ZPRUYC5A",
    },
    {
        "id": 2,
        "BankSlipDate": "2022-04-17",
        "CustomerID": "XYCP1J12",
        "BankCode": "0LCW",
        "BankSlipCurrency": "GBP",
        "BankSlipAmount": "2106.00",
        "CustomerName": "Google",
        "BankSlipCustomer": "9MZV6T",
        "Country": "Taiwan",
        "FilePath": "/files/DCGIC560BV.pdf",
        "PredictType": "F",
        "ProcessStatus": "Wait-For-Check",
        "ReferenceNumber": "J2I8K5C2RSWO",
        "RemitType": "Branch",
        "BankSlipRemark": "Remark 2",
        "ChangeDate": "2021-11-13",
        "ArNo": "NW7HQ0JTE2",
    },
    {
        "id": 3,
        "BankSlipDate": "2022-12-01",
        "CustomerID": "WSW8J9B8",
        "BankCode": "M22N",
        "BankSlipCurrency": "TWD",
        "BankSlipAmount": "1105.00",
        "CustomerName": "NVIDIA",
        "BankSlipCustomer": "GHS6N1",
        "Country": "UK",
        "FilePath": "/files/P4GDTNFMNQ.pdf",
        "PredictType": "A",
        "ProcessStatus": "Wait-For-Check",
        "ReferenceNumber": "96JZYUQSUAN0",
        "RemitType": "Online",
        "BankSlipRemark": "Remark 40",
        "ChangeDate": "2020-04-02",
        "ArNo": "4P3L2HGDXD",
    },
    {
        "id": 4,
        "BankSlipDate": "2023-01-15",
        "CustomerID": "HJK9L2M8",
        "BankCode": "G34P",
        "BankSlipCurrency": "USD",
        "BankSlipAmount": "1578.50",
        "CustomerName": "Samsung",
        "BankSlipCustomer": "TXY8V2",
        "Country": "US",
        "FilePath": "/files/NOP4TKV5LQ.pdf",
        "PredictType": "B",
        "ProcessStatus": "In-Progress",
        "ReferenceNumber": "7QWZBXRYTDU2",
        "RemitType": "Wire",
        "BankSlipRemark": "Remark 21",
        "ChangeDate": "2021-07-18",
        "ArNo": "9G5R1KJCXY",
    },
    {
        "id": 5,
        "BankSlipDate": "2023-05-22",
        "CustomerID": "RTY3E1J7",
        "BankCode": "X17A",
        "BankSlipCurrency": "EUR",
        "BankSlipAmount": "2340.75",
        "CustomerName": "Intel",
        "BankSlipCustomer": "WOP9D4",
        "Country": "DE",
        "FilePath": "/files/BVMP2EHFZW.pdf",
        "PredictType": "A",
        "ProcessStatus": "Completed",
        "ReferenceNumber": "4XZUJVRLTSY6",
        "RemitType": "Cash",
        "BankSlipRemark": "Remark 33",
        "ChangeDate": "2022-11-23",
        "ArNo": "2J9H4QPGVK",
    },
    {
        "id": 6,
        "BankSlipDate": "2023-07-30",
        "CustomerID": "JHY6C5L2",
        "BankCode": "Q89K",
        "BankSlipCurrency": "JPY",
        "BankSlipAmount": "451000.00",
        "CustomerName": "Amazon",
        "BankSlipCustomer": "ZKY7W9",
        "Country": "JP",
        "FilePath": "/files/YGRU4KLJTN.pdf",
        "PredictType": "C",
        "ProcessStatus": "Wait-For-Check",
        "ReferenceNumber": "3LMNKWQSTXV5",
        "RemitType": "Online",
        "BankSlipRemark": "Remark 19",
        "ChangeDate": "2023-02-05",
        "ArNo": "1K8J3XHDZL",
    },
    {
        "id": 7,
        "BankSlipDate": "2023-10-10",
        "CustomerID": "ZQX8M4R1",
        "BankCode": "L56G",
        "BankSlipCurrency": "GBP",
        "BankSlipAmount": "980.00",
        "CustomerName": "Microsoft",
        "BankSlipCustomer": "OPQ2F8",
        "Country": "UK",
        "FilePath": "/files/DFKL5MNGHT.pdf",
        "PredictType": "A",
        "ProcessStatus": "Pending",
        "ReferenceNumber": "6ABCDXSTUV9",
        "RemitType": "Wire",
        "BankSlipRemark": "Remark 28",
        "ChangeDate": "2023-06-12",
        "ArNo": "3L2P1KJHNB",
    },
    {
        "id": 8,
        "BankSlipDate": "2023-12-05",
        "CustomerID": "BVR2Q3N6",
        "BankCode": "S71V",
        "BankSlipCurrency": "CNY",
        "BankSlipAmount": "7598.00",
        "CustomerName": "Apple",
        "BankSlipCustomer": "LVH8T7",
        "Country": "CN",
        "FilePath": "/files/TKFM3PLNVR.pdf",
        "PredictType": "B",
        "ProcessStatus": "Completed",
        "ReferenceNumber": "5NOMQWZLXU8",
        "RemitType": "Cash",
        "BankSlipRemark": "Remark 37",
        "ChangeDate": "2023-09-21",
        "ArNo": "5F9C7HBGJP",
    },
    {
        "id": 9,
        "BankSlipDate": "2024-08-15",
        "CustomerID": "QWB4C5T6",
        "BankCode": "C5D9",
        "BankSlipCurrency": "USD",
        "BankSlipAmount": "1234.00",
        "CustomerName": "Meta",
        "BankSlipCustomer": "VCH6L5",
        "Country": "US",
        "FilePath": "/files/2M3L3KJH4N.pdf",
        "PredictType": "F",
        "ProcessStatus": "Wait-For-Check",
        "ReferenceNumber": "2QWERTYUIO0",
        "RemitType": "Online",
        "BankSlipRemark": "Remark 5",
        "ChangeDate": "2024-04-18",
        "ArNo": "9K8J7H6G5F",
    },
    {
        "id": 10,
        "BankSlipDate": "2024-08-24",
        "CustomerID": "QWARTAUI",
        "BankCode": "T5A9",
        "BankSlipCurrency": "JPY",
        "BankSlipAmount": "123466.00",
        "CustomerName": "IBM",
        "BankSlipCustomer": "VAC6L2",
        "Country": "JP",
        "FilePath": "/files/2M9LGKJCN.pdf",
        "PredictType": "F",
        "ProcessStatus": "Wait-For-Check",
        "ReferenceNumber": "2QWERTYUIO0",
        "RemitType": "In-Branch",
        "BankSlipRemark": "Remark 4",
        "ChangeDate": "2024-04-18",
        "ArNo": "9K8J78C5F",
    },
]

sap_lst = [
    {"id": 1, "CustomerID": "SQ75BAGU", "CustomerName": "TSMC"},
    {"id": 2, "CustomerID": "BVR2Q3N6", "CustomerName": "Apple"},
    {"id": 3, "CustomerID": "ZQX8M4R1", "CustomerName": "Microsoft"},
    {"id": 4, "CustomerID": "XYCP1J12", "CustomerName": "Google"},
    {"id": 5, "CustomerID": "JHY6C5L2", "CustomerName": "Amazon"},
    {"id": 6, "CustomerID": "HJK9L2M8", "CustomerName": "Samsung"},
    {"id": 7, "CustomerID": "RTY3E1J7", "CustomerName": "Intel"},
    {"id": 8, "CustomerID": "WSW8J9B8", "CustomerName": "NVIDIA"},
    {"id": 9, "CustomerID": "QWB4C5T6", "CustomerName": "Meta"},
    {"id": 10, "CustomerID": "QWARTAUI", "CustomerName": "IBM"},
]

special_customer_lst = [
    {"id": 1, "CustomerName": "Meta"},
    {"id": 2, "CustomerName": "Amazon"},
]
